### ISSUE TITLE
Mina Protocol Community

### ISSUE THREAD

**Issue by Jaddddd** [Trivo25/mina-view#28]
Please add this picture to it, please:

![photo_2021-09-28_16-52-06](https://user-images.githubusercontent.com/24520541/135111784-12f952f9-c2e9-4f6b-b6d7-09435ea2dc50.jpg)
:

**Comment by Jaddddd** [comment]
also our official twitter: https://twitter.com/CommunityMina

**Comment by Trivo25** [comment]
done, thanks!
